FROM keymetrics/pm2:10-alpine

RUN echo -e 'http://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/community\nhttp://dl-cdn.alpinelinux.org/alpine/edge/testing' > /etc/apk/repositories
RUN apk add --no-cache yarn git

WORKDIR /app

COPY . .

WORKDIR /app/proxy
RUN yarn

EXPOSE 3000

ENV NODE_ENV="production"

CMD [ "pm2-docker", "start", "pm2.config.js" ]